version: '2'

services:

    fiks:
      restart: always
      build : .
      container_name: fiks
      volumes:
      - ./src:/var/www/html
      networks:
      - web
      ports:
      - "8210:80"
      labels:
      - "traefik.enable=false"

networks:
  web:
   name: webserver_network
   external: true
